const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav-links');if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}))}
const items=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});items.forEach(i=>observer.observe(i))}else items.forEach(i=>i.classList.add('visible'));
const form=document.querySelector('[data-prototype-form]');if(form)form.addEventListener('submit',e=>{e.preventDefault();const status=form.querySelector('.form-status');status.classList.add('show');status.focus();form.reset()});
const pagePhoto={
  '/services.html':{src:'images/services-wellness-exam.jpg',alt:"A veterinarian listening to a relaxed black Labrador's heart during a wellness exam",caption:'Careful observation, familiar hands, and time to ask every question.',className:''},
  '/about.html':{src:'images/about-team-huddle.jpg',alt:"A fictional veterinary care team reviewing the day's plan together in a sunlit clinic",caption:'Connected teams make for calmer, more consistent care.',className:'offset'},
  '/resources.html':{src:'images/resources-cat-care.jpg',alt:'An orange tabby cat being gently brushed at home beside a sunny window',caption:'Everyday rituals can reveal useful changes in comfort, coat, and behavior.',className:'warm'}
};
const photo=pagePhoto[location.pathname];if(photo){const hero=document.querySelector('.page-hero');const figure=document.createElement('figure');figure.className=`editorial-photo reveal ${photo.className}`;const img=document.createElement('img');img.src=photo.src;img.alt=photo.alt;const caption=document.createElement('figcaption');caption.textContent=photo.caption;figure.append(img,caption);hero.insertAdjacentElement('afterend',figure);requestAnimationFrame(()=>figure.classList.add('visible'))}
