from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://brookeleininger.github.io/FayettevilleAnimalHospital/"

services = [
 ("wellness-exams","Wellness Exams","Preventive visits that establish your pet's healthy baseline and catch meaningful changes early.","Annual or semiannual exams help us understand your pet before illness changes the picture.","We review daily habits, perform a nose-to-tail exam, discuss age-appropriate screening, and build a practical plan together.",["vaccinations","parasite-prevention"]),
 ("vaccinations","Pet Vaccinations","Individual vaccine plans for dogs and cats based on age, health, lifestyle, and local exposure.","Vaccines protect pets from serious infectious diseases and are especially important during early life, travel, boarding, and lifestyle changes.","Your veterinarian reviews prior records and risk factors, explains core and optional vaccines, and creates a schedule that avoids unnecessary treatment.",["wellness-exams","puppy-kitten-care"]),
 ("parasite-prevention","Parasite Prevention","Year-round protection from heartworms, fleas, ticks, and intestinal parasites in Northwest Arkansas.","Warm seasons and active outdoor lifestyles make consistent prevention important for both indoor and outdoor pets.","We match testing and prevention to species, weight, age, health history, and exposure, then help you keep the schedule manageable.",["wellness-exams","vaccinations"]),
 ("dental-care","Pet Dental Care","Oral assessments, professional cleanings, dental imaging, and treatment for dogs and cats.","Bad breath, difficulty chewing, drooling, visible tartar, or pawing at the mouth can signal painful dental disease.","Dental care begins with an awake oral assessment. When a cleaning is recommended, we explain anesthesia, imaging, monitoring, findings, and home care.",["diagnostics","pet-surgery"]),
 ("diagnostics","Veterinary Diagnostics","Laboratory testing and diagnostic imaging that help turn symptoms into informed next steps.","Testing may be recommended when an exam reveals a concern, symptoms persist, or routine screening could identify early disease.","We begin with the most useful questions, select appropriate tests, and discuss results in plain language before deciding what comes next.",["urgent-sick-care","wellness-exams"]),
 ("pet-surgery","Pet Surgery","Thoughtful surgical planning, attentive monitoring, pain control, and supported recovery.","Surgery may address a routine preventive need, a painful condition, an injury, or a diagnostic finding.","We review pre-anesthetic testing, the procedure, monitoring, pain management, home instructions, and follow-up before surgery day.",["spay-neuter","diagnostics"]),
 ("spay-neuter","Spay & Neuter","Routine reproductive surgery with individualized timing and careful perioperative support.","Timing depends on species, breed, age, health, lifestyle, and family goals; there is no single schedule for every pet.","A preoperative visit confirms health and timing. Families receive fasting instructions, same-day updates, medication guidance, and recovery expectations.",["pet-surgery","puppy-kitten-care"]),
 ("senior-pet-care","Senior Pet Care","Proactive monitoring and comfort-focused planning for aging dogs and cats.","Changes in mobility, sleep, appetite, thirst, weight, or interaction deserve attention even when they seem subtle.","Senior visits allow more time for trend review, a thorough exam, screening recommendations, and realistic plans that protect comfort and connection.",["diagnostics","nutrition-weight-management"]),
 ("puppy-kitten-care","Puppy & Kitten Care","A confident start with exams, vaccines, parasite care, nutrition, and behavior guidance.","Young pets change quickly and benefit from several planned visits during their first months at home.","Each visit builds on the last, addressing growth, prevention, social development, home routines, and the questions that arise between appointments.",["vaccinations","spay-neuter"]),
 ("urgent-sick-care","Urgent & Sick Care","Prompt evaluation for established patients when a pet is injured, uncomfortable, or suddenly not themselves.","Call when you notice persistent vomiting, diarrhea, coughing, limping, appetite loss, urinary changes, wounds, or marked behavior changes.","Our team gathers a focused history, checks stability, examines your pet, and explains whether treatment, testing, monitoring, or emergency referral is appropriate.",["diagnostics","wellness-exams"]),
 ("nutrition-weight-management","Nutrition & Weight Management","Practical nutrition plans that support healthy growth, weight, mobility, and chronic-condition care.","Body condition changes, confusing food choices, life-stage transitions, or medical conditions can make tailored guidance useful.","We assess body and muscle condition, review food and treats, estimate needs, and set measurable goals without judgment or crash diets.",["wellness-exams","senior-pet-care"]),
 ("behavioral-consultations","Behavioral Consultations","Medical-minded support for behavior changes, fear, house-soiling, and everyday challenges.","Sudden behavior changes can reflect pain or illness; ongoing concerns may benefit from structured observation and a coordinated plan.","We review context, patterns, health, environment, and safety, then outline management steps and referral options when specialized care is needed.",["diagnostics","wellness-exams"]),
]

life_stages = [
 ("puppy-care","Puppy Care","Build a healthy foundation during your puppy's fast-changing first year.","Puppy care combines a series of exams with vaccines, parasite prevention, nutrition, social development, and positive handling.","Bring prior records, a list of foods and preventives, and your questions. We will map the next several visits so the plan feels predictable.","puppy-kitten-care","new-puppy-checklist"),
 ("kitten-care","Kitten Care","Support healthy growth and confident veterinary visits from the very beginning.","Kitten visits address infectious-disease protection, parasite screening, nutrition, litter habits, enrichment, and safe introductions.","We adapt handling to your kitten's comfort, review their home environment, and create a clear schedule for upcoming care.","puppy-kitten-care","new-kitten-checklist"),
 ("adult-dog-care","Adult Dog Care","Keep active adult dogs well with prevention shaped around real life in Northwest Arkansas.","Annual exams create continuity while vaccines, heartworm prevention, dental health, weight, and behavior needs evolve.","We compare current findings with prior visits and focus on sustainable habits that protect long-term health.","wellness-exams","dog-wellness-frequency"),
 ("adult-cat-care","Adult Cat Care","Thoughtful preventive care for cats, including those who live entirely indoors.","Cats often mask discomfort, making routine exams and careful discussion of home behavior especially valuable.","Low-stress handling, carrier planning, oral health, weight trends, and urinary habits all inform the care plan.","wellness-exams","cat-wellness-frequency"),
 ("senior-dog-care","Senior Dog Care","Help older dogs stay comfortable, engaged, and connected through changing needs.","Senior timing varies by size and breed, but closer observation becomes useful as mobility, senses, and organ function change.","More frequent exams and selected screening can reveal manageable problems before they become crises.","senior-pet-care","when-dog-is-senior"),
 ("senior-cat-care","Senior Cat Care","Protect comfort and independence as your cat enters their later chapters.","Weight loss, reduced jumping, grooming changes, thirst, and litter-box habits can be early health clues in older cats.","We combine gentle exams, trend review, and appropriate testing with home strategies that make daily life easier.","senior-pet-care","when-cat-is-senior"),
]

articles = [
 ("dog-wellness-frequency","How Often Should My Dog Have a Wellness Exam?","A practical guide to wellness-exam frequency for dogs at different ages and health stages.","Most healthy adult dogs benefit from an exam at least once a year, while puppies, seniors, and dogs managing health conditions often need more frequent visits.","Age is only one factor. Breed, medications, travel, outdoor exposure, behavior, and previous findings help determine the most useful schedule.","wellness-exams"),
 ("cat-wellness-frequency","How Often Should My Cat Visit the Veterinarian?","Why indoor and outdoor cats need routine veterinary visits and how frequency changes with age.","Healthy adult cats generally benefit from yearly exams. Kittens, seniors, and cats with ongoing concerns may need closer follow-up.","Cats can hide discomfort remarkably well. Weight, muscle condition, teeth, heart, kidneys, joints, and subtle behavior changes deserve regular attention.","wellness-exams"),
 ("puppy-vaccines","What Vaccines Does My Puppy Need?","Understand core puppy vaccines, timing, boosters, and lifestyle-based protection.","Puppies need a carefully timed vaccine series because protection from maternal antibodies fades unpredictably during early life.","Core protection commonly includes distemper, adenovirus, parvovirus, and rabies. Other vaccines depend on environment, travel, boarding, and exposure.","vaccinations"),
 ("kitten-vaccines","What Vaccines Does My Kitten Need?","A clear overview of kitten vaccine series, boosters, and individual risk assessment.","Kitten vaccines are given as a series to build reliable protection while early maternal immunity declines.","Core recommendations commonly address feline viral rhinotracheitis, calicivirus, panleukopenia, and rabies; individual risk guides other choices.","vaccinations"),
 ("dental-disease-signs","Signs Your Pet May Have Dental Disease","Recognize common and easily missed signs of painful oral disease in dogs and cats.","Persistent bad breath, tartar, red gums, dropping food, chewing on one side, facial swelling, or reduced interest in toys can indicate dental disease.","Many pets continue eating despite pain. An oral assessment and dental imaging under anesthesia may be needed to understand disease below the gumline.","dental-care"),
 ("brush-dog-teeth","How to Brush Your Dog's Teeth","A gradual, pet-friendly approach to building a useful home dental-care routine.","Begin with brief handling around the muzzle, then introduce pet toothpaste before adding a soft toothbrush or finger brush.","Keep sessions short and positive. Never use human toothpaste, and stop if your dog shows pain or significant resistance.","dental-care"),
 ("brush-cat-teeth","How to Brush Your Cat's Teeth","Gentle steps for introducing tooth brushing without turning it into a daily struggle.","Start when your cat is relaxed, reward face handling, and slowly progress from tasting pet toothpaste to touching the outer tooth surfaces.","Even several short sessions each week can be useful. A veterinarian should evaluate redness, odor, drooling, or apparent mouth pain first.","dental-care"),
 ("when-dog-is-senior","When Is a Dog Considered a Senior?","Learn how size, breed, and individual health influence when senior-dog care begins.","Large dogs often enter their senior years earlier than small dogs, so a calendar age alone does not tell the full story.","Senior care focuses on trends in mobility, senses, sleep, weight, organ function, and quality of life rather than applying a label.","senior-pet-care"),
 ("when-cat-is-senior","When Is a Cat Considered a Senior?","Understand feline aging and the subtle changes worth discussing with your veterinarian.","Many cats are considered senior around age ten, although preventive planning may intensify earlier based on health and history.","Because aging cats often conceal discomfort, small changes in jumping, grooming, appetite, or social behavior matter.","senior-pet-care"),
 ("preparing-for-pet-surgery","Preparing Your Pet for Surgery","A calm checklist for fasting, medications, arrival, transportation, and questions before surgery.","Follow the clinic's instructions exactly because fasting and medication directions vary by age, condition, and procedure.","Prepare a safe ride, a quiet recovery space, current medication information, and a reliable phone number for updates.","pet-surgery"),
 ("after-pet-surgery","What to Expect After Your Pet's Surgery","Know what recovery can look like and which changes should prompt a call.","Sleepiness, a reduced appetite, and mild activity changes can occur after anesthesia, but instructions differ by procedure.","Monitor the incision, prevent licking, give medications as directed, restrict activity, and call about bleeding, opening, worsening swelling, repeated vomiting, or severe lethargy.","pet-surgery"),
 ("signs-pet-in-pain","Common Signs Your Pet May Be in Pain","Behavioral and physical clues that dogs and cats may show when they hurt.","Pain may appear as hiding, restlessness, panting, guarding, reduced grooming, reluctance to jump, appetite changes, or unusual irritability.","Do not give human pain medication. Record what you notice and contact a veterinarian for safe evaluation and treatment.","urgent-sick-care"),
 ("flea-tick-arkansas","Flea and Tick Prevention in Arkansas","Why Northwest Arkansas pets often benefit from consistent, year-round parasite protection.","Warm periods, wooded trails, wildlife, and household environments can sustain flea and tick exposure beyond peak summer.","Use a veterinarian-recommended product for your pet's species and weight. Dog products containing permethrin can be dangerous to cats.","parasite-prevention"),
 ("heartworm-arkansas","Heartworm Prevention in Arkansas","Understand heartworm transmission, testing, and prevention for Arkansas dogs and cats.","Mosquitoes transmit heartworms, and Arkansas weather supports meaningful exposure. Indoor pets are not fully protected from mosquitoes.","Consistent prevention is safer and simpler than treating established disease. Dogs also need testing on a veterinarian-recommended schedule.","parasite-prevention"),
 ("seasonal-allergies-dogs","Seasonal Allergies in Dogs","Recognize common allergy patterns and learn why itching deserves a veterinary plan.","Paw licking, recurrent ear trouble, rubbing, redness, and skin infections may increase during certain seasons.","Similar symptoms can have different causes, including parasites and infection, so effective relief starts with an examination rather than guesswork.","behavioral-consultations"),
 ("comfortable-cat-vet","Helping Your Cat Feel Comfortable at the Vet","Carrier, travel, and home strategies that can reduce stress before a veterinary visit.","Leave the carrier out as familiar furniture, add comfortable bedding, practice brief car sessions, and avoid chasing your cat just before departure.","Tell the clinic about prior fear or motion sickness. Pre-visit medication may be appropriate for some cats when prescribed in advance.","wellness-exams"),
 ("healthy-weight-dogs","Healthy Weight Guidelines for Dogs","Use body condition, muscle condition, and daily habits to understand your dog's healthy weight.","A healthy weight is not a universal number. Breed build, age, muscle, and body condition all matter.","Measure food, account for treats, track weight trends, and choose gradual changes. Sudden weight gain or loss warrants evaluation.","nutrition-weight-management"),
 ("healthy-weight-cats","Healthy Weight Guidelines for Cats","Practical feeding, enrichment, and monitoring guidance for feline weight management.","Cats need gradual, carefully planned weight change because overly rapid loss can be dangerous.","Measured meals, play, food puzzles, household feeding coordination, and regular reassessment support safe progress.","nutrition-weight-management"),
 ("new-puppy-checklist","New Puppy Checklist","A practical first-week checklist for supplies, safety, routines, records, and veterinary care.","Prepare a secure sleep area, age-appropriate food, identification, safe toys, cleaning supplies, and a plan for supervised bathroom breaks before your puppy arrives.","Schedule a veterinary visit soon after adoption, bring every available record, and limit exposure to high-risk public areas until your veterinarian explains vaccine protection.","puppy-kitten-care"),
 ("new-kitten-checklist","New Kitten Checklist","Prepare a calm home, useful supplies, and a strong preventive-care start for a new kitten.","Set up a quiet introductory room with food, water, a hiding place, scratching options, safe toys, and at least one accessible litter box.","Arrange an early veterinary visit, bring adoption and vaccine records, and discuss parasite screening, nutrition, household introductions, and safe enrichment.","puppy-kitten-care"),
]

conditions = [
 ("ear-infections","Ear Infections in Dogs and Cats","Understand signs of ear inflammation and why recurring infections need a closer look.","Head shaking, scratching, odor, redness, debris, or pain can occur with infection, allergies, mites, foreign material, or other disease.","Avoid placing leftover medication or harsh cleaners in a painful ear. An exam and ear sample help guide safe, targeted treatment.","urgent-sick-care"),
 ("skin-allergies","Skin Allergies and Itching","A practical overview of itchy skin, common triggers, and the value of a structured workup.","Fleas, environmental allergies, food reactions, infection, and other conditions can create similar scratching and licking patterns.","Contact a veterinarian when itching is persistent, sleep-disrupting, causes wounds, or comes with odor, hair loss, or ear trouble.","diagnostics"),
 ("vomiting-diarrhea","Vomiting and Diarrhea","Know what information helps your veterinarian and when stomach upset becomes urgent.","Diet changes, parasites, infection, toxins, foreign objects, and systemic illness are among many possible causes.","Urgent evaluation is appropriate for repeated symptoms, blood, pain, weakness, dehydration, toxin exposure, or a pet who cannot keep water down.","urgent-sick-care"),
 ("pet-limping","Limping and Mobility Changes","Learn how to observe a limp safely and recognize signs that need prompt veterinary attention.","Limping may involve paws, nails, muscles, joints, bones, or nerves, and dogs and cats may compensate in subtle ways.","Restrict strenuous activity and avoid manipulating a painful limb. Seek prompt care for severe pain, swelling, trauma, or inability to bear weight.","diagnostics"),
 ("urinary-issues","Urinary Issues in Pets","Recognize changes in urination that can signal discomfort or a time-sensitive emergency.","Straining, frequent trips, accidents, blood, crying, licking, or changes in urine volume all deserve attention.","A pet repeatedly trying but unable to pass urine needs emergency evaluation, especially a male cat.","urgent-sick-care"),
 ("pet-obesity","Obesity in Dogs and Cats","Understand health effects of excess weight and the building blocks of a safe plan.","Excess weight can affect mobility, breathing, heat tolerance, skin health, and management of other conditions.","Weight plans should protect nutrition and muscle. A veterinarian can calculate a starting target and check for medical contributors.","nutrition-weight-management"),
 ("pet-arthritis","Arthritis and Chronic Joint Pain","Common signs of arthritis and home changes that can support comfortable movement.","Slower rising, reduced jumping, stiffness, slipping, shorter walks, irritability, or grooming changes can reflect joint pain.","Treatment may combine weight management, home modifications, exercise changes, medication, and monitoring; never use human pain relievers.","senior-pet-care"),
 ("pet-anxiety","Anxiety and Fear in Pets","Recognize stress signals and build a compassionate plan for fearful behavior.","Pacing, hiding, vocalizing, destruction, house-soiling, freezing, or aggression can occur when a pet feels unsafe.","Sudden changes need a medical evaluation. Behavior support may include management, gradual training, medication, and qualified referral.","behavioral-consultations"),
]

team = [
 ("mara-ellison-dvm","Dr. Mara Ellison","Veterinarian","Preventive medicine and puppy and kitten care","Ozark College of Veterinary Medicine, fictional DVM","Mara values clear explanations and enjoys helping new pet families build routines that last. Her fictional clinical interests include preventive care, behavior-aware handling, and the small observations that reveal meaningful change."),
 ("theo-bennett-dvm","Dr. Theo Bennett","Veterinarian","Internal medicine and senior pet care","River Valley University, fictional DVM","Theo is drawn to complex puzzles and unhurried conversations. His fictional practice style centers on interpreting trends, explaining choices plainly, and protecting comfort for aging pets."),
 ("nina-solis-dvm","Dr. Nina Solis","Veterinarian","Dentistry and soft-tissue surgery","Heartland Veterinary Institute, fictional DVM","Nina brings a methodical, gentle approach to procedures and recovery planning. Her fictional interests include oral health, surgical safety, and helping families know what to expect."),
 ("lena-park","Lena Park","Practice Lead","Client experience and low-stress visits","Northwest Arkansas Community College, fictional background","Lena connects the details that make visits feel calmer—from scheduling and communication to thoughtful accommodations for pets who need more time. Her identity and biography are entirely fictional."),
]

support = [
 ("new-patients","New Patients","Everything new clients need to begin care with Fayetteville Animal Hospital.","Welcome to our fictional practice","Before the first visit, gather prior medical records, current medication and prevention details, food information, and a list of questions. Sending records ahead gives the clinical team time to understand the history.","Arrive a few minutes early and keep cats in secure carriers and dogs on non-retractable leashes. Tell us before arrival if your pet needs extra space or has had a difficult visit elsewhere."),
 ("what-to-expect","What to Expect","A clear guide to appointments, communication, recommendations, and follow-up.","Visits built around listening","A veterinary assistant begins with your concerns and your pet's recent routine. The veterinarian then performs an exam, discusses findings, and explains any recommendations before moving forward.","Some answers are immediate; others require testing or observation over time. We provide next steps and invite questions so you leave knowing what to monitor."),
 ("payment-information","Payment Information","Prototype payment policies and planning information for this fictional veterinary practice.","Clear conversations about cost","Fayetteville Animal Hospital is fictional and does not accept payment. In a real practice, estimates would be reviewed before non-emergency services and payment would be due when care is provided.","A realistic practice may accept major cards and pet insurance reimbursement while offering written estimates for procedures. Financial conversations should happen early and without judgment."),
 ("faq","Frequently Asked Questions","Answers to common questions about appointments, records, prescriptions, and hospital policies.","Helpful answers before your visit","Call before arriving for urgent concerns so the team can assess timing and direct you appropriately. Routine appointment requests may be made through the prototype form, which does not transmit information.","Bring medications in original packaging and request prescription refills before running out. Written authorization is typically required before records are shared with another hospital."),
 ("emergency-information","Emergency Information","How to recognize urgent warning signs and seek appropriate emergency veterinary care.","Know where to go","Fayetteville Animal Hospital is not a 24-hour emergency facility. Difficulty breathing, collapse, uncontrolled bleeding, major trauma, prolonged seizures, toxin exposure, or inability to urinate may require immediate emergency care.","Call the nearest open emergency veterinary hospital while preparing to leave. Do not delay for an online response, and do not induce vomiting unless a veterinary professional specifically instructs you to do so."),
]

def rel(depth, path): return "../" * depth + path

def header(depth, active=""):
 p = "../" * depth
 def current(name): return ' aria-current="page"' if active == name else ""
 return f'''<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container nav-wrap"><a class="brand" href="{p}index.html" aria-label="Fayetteville Animal Hospital home"><svg class="brand-mark" viewBox="0 0 36 44" aria-hidden="true"><path d="M18 1C10 8 4 15 4 25c0 10 6 17 14 18 8-1 14-8 14-18C32 15 26 8 18 1Z" fill="none" stroke="currentColor"/><path d="M18 11v22M10 23h16" stroke="currentColor"/></svg><span>Fayetteville<br>Animal Hospital</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="nav">Menu</button><nav id="nav" class="nav-links" aria-label="Primary"><a{current('home')} href="{p}index.html">Home</a><a{current('about')} href="{p}about.html">About</a><a{current('services')} href="{p}services.html">Services</a><a{current('resources')} href="{p}resources.html">Resources</a><a{current('contact')} href="{p}contact.html">Contact</a><a class="button" href="{p}contact.html#appointment">Request an Appointment</a></nav></div></header>'''

def footer(depth):
 p = "../" * depth
 return f'''<footer class="site-footer"><div class="container"><div class="footer-grid"><div><div class="footer-brand">Fayetteville Animal Hospital</div><p style="color:#aabdb0">Care for every chapter.</p></div><div class="footer-col"><h2>Plan a visit</h2><a href="{p}new-patients.html">New patients</a><a href="{p}what-to-expect.html">What to expect</a><a href="{p}payment-information.html">Payment information</a><a href="{p}faq.html">FAQ</a></div><div class="footer-col"><h2>Care</h2><a href="{p}services.html">Services</a><a href="{p}pet-care/puppy-care.html">Puppy care</a><a href="{p}pet-care/senior-cat-care.html">Senior cat care</a><a href="{p}emergency-information.html">Emergency information</a></div><div class="footer-col"><h2>Explore</h2><a href="{p}about.html">About</a><a href="{p}resources.html">Resources</a><a href="{p}contact.html">Contact</a></div></div><div class="footer-bottom"><span>© 2026 Fayetteville Animal Hospital</span><span class="disclosure">Fayetteville Animal Hospital is a fictional veterinary practice created for development and testing purposes.</span></div></div></footer>'''

def page(path, title, description, h1, eyebrow, crumb, body, active, depth=1):
 canonical = BASE + path
 css = rel(depth, "css/style.css")
 js = rel(depth, "js/script.js")
 html = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Fayetteville Animal Hospital</title><meta name="description" content="{escape(description, quote=True)}"><link rel="canonical" href="{canonical}"><link rel="stylesheet" href="{css}"><script src="{js}" defer></script></head><body>{header(depth,active)}<main id="main"><section class="page-hero compact"><div class="container narrow"><div class="crumbs">{crumb}</div><span class="eyebrow">{escape(eyebrow)}</span><h1>{escape(h1)}</h1><p class="lead">{escape(description)}</p></div></section>{body}</main>{footer(depth)}</body></html>'''
 target = ROOT / path
 target.parent.mkdir(parents=True, exist_ok=True)
 target.write_text(html, encoding="utf-8")

def related_cards(items, depth=1):
 return '<div class="related"><span class="eyebrow">Related reading</span><div class="related-grid">' + ''.join(f'<a href="{rel(depth,url)}">{escape(label)}</a>' for url,label in items) + '</div></div>'

service_names = {slug:name for slug,name,*_ in services}
article_names = {slug:title for slug,title,*_ in articles}

for slug,name,summary,need,expect,related in services:
 links=[(f"services/{r}.html",service_names[r]) for r in related]
 body=f'''<section class="section section-paper"><div class="container content-shell"><article class="prose"><h2>Care with a longer view</h2><p>{escape(summary)} Our recommendations reflect the individual pet, current evidence, and the family's priorities rather than a one-size-fits-all protocol.</p><h2>When this service may help</h2><p>{escape(need)}</p><p>Contact us when a change is persistent, worsening, painful, or simply concerning. A conversation can help determine whether a routine appointment, prompt visit, or emergency hospital is the right next step.</p><h2>What to expect</h2><p>{escape(expect)}</p><h3>Designed around your pet</h3><ul><li>A focused history and attentive physical examination</li><li>Clear discussion before tests or treatment</li><li>Written next steps and signs to monitor at home</li><li>Coordination with specialty or emergency care when appropriate</li></ul>{related_cards(links + [("resources.html","Browse the pet owner resource library")])}</article><aside class="page-aside"><h2>Service navigation</h2><a href="../services.html">All veterinary services</a><a href="../new-patients.html">New patient information</a><a href="../what-to-expect.html">What to expect</a><a class="button" href="../contact.html#appointment">Request an appointment</a></aside></div></section>'''
 page(f"services/{slug}.html",name,f"Learn about {name.lower()} for dogs and cats at our fictional Fayetteville veterinary practice.",name,"Veterinary services",f'<a href="../index.html">Home</a> / <a href="../services.html">Services</a> / {escape(name)}',body,"services")

for slug,name,summary,intro,expect,service,article in life_stages:
 body=f'''<section class="section section-paper"><div class="container content-shell"><article class="prose"><h2>Care for this chapter</h2><p>{escape(intro)}</p><p>{escape(summary)} The most useful plan changes as your pet grows, and continuity helps small observations become meaningful.</p><h2>What we pay attention to</h2><ul><li>Changes in weight, appetite, thirst, sleep, and activity</li><li>Dental health, mobility, skin, coat, and behavior</li><li>Vaccination and parasite risks shaped by daily life</li><li>Questions about nutrition, enrichment, and home routines</li></ul><h2>Planning the next visit</h2><p>{escape(expect)}</p>{related_cards([(f"services/{service}.html",service_names[service]),(f"resources/articles/{article}.html",article_names[article]),("resources.html","Explore all pet care resources")])}</article><aside class="page-aside"><h2>Life-stage care</h2><a href="puppy-care.html">Puppy care</a><a href="kitten-care.html">Kitten care</a><a href="adult-dog-care.html">Adult dog care</a><a href="adult-cat-care.html">Adult cat care</a><a href="senior-dog-care.html">Senior dog care</a><a href="senior-cat-care.html">Senior cat care</a><a class="button" href="../contact.html#appointment">Request an appointment</a></aside></div></section>'''
 page(f"pet-care/{slug}.html",name,f"A practical guide to {name.lower()} from Fayetteville Animal Hospital's fictional veterinary team.",name,"Life-stage care",f'<a href="../index.html">Home</a> / <a href="../resources.html">Resources</a> / {escape(name)}',body,"resources")

for slug,title,meta,intro,detail,service in articles:
 body=f'''<section class="section section-paper"><div class="container content-shell"><article class="prose"><div class="resource-note"><strong>Educational note:</strong> This general information cannot diagnose a pet or replace an examination.</div><h2>The short answer</h2><p>{escape(intro)}</p><h2>Why the details matter</h2><p>{escape(detail)}</p><p>Your pet's age, history, environment, medications, and recent changes all affect what advice is appropriate. Keep notes about timing, frequency, appetite, activity, and anything that makes the concern better or worse.</p><h2>When to contact a veterinarian</h2><p>Call when a change is persistent, recurring, painful, worsening, or accompanied by weakness, breathing trouble, repeated vomiting, bleeding, collapse, or difficulty urinating. Emergency signs should not wait for an online response.</p><h2>How we can help</h2><p>A veterinary visit brings the history, physical examination, and—when useful—targeted testing together. The goal is not simply to name a problem, but to create a safe and realistic next step.</p>{related_cards([(f"services/{service}.html",service_names[service]),("resources.html","Return to the resource library"),("contact.html","Contact the hospital")],2)}</article><aside class="page-aside"><h2>Resource library</h2><a href="../../resources.html">All resources</a><a href="../conditions/ear-infections.html">Care and condition guides</a><a href="../../faq.html">Frequently asked questions</a><a class="button" href="../../contact.html#appointment">Request an appointment</a></aside></div></section>'''
 page(f"resources/articles/{slug}.html",title,meta,title,"Pet owner guide",f'<a href="../../index.html">Home</a> / <a href="../../resources.html">Resources</a> / {escape(title)}',body,"resources",2)

for slug,title,meta,intro,detail,service in conditions:
 body=f'''<section class="section section-paper"><div class="container content-shell"><article class="prose"><div class="resource-note"><strong>Important:</strong> This guide supports informed observation but does not provide a diagnosis.</div><h2>What owners may notice</h2><p>{escape(intro)}</p><p>Write down when signs began, how often they occur, recent changes, and any photos or videos that may help. Avoid giving leftover or human medication unless a veterinarian directs you.</p><h2>Why an examination matters</h2><p>{escape(detail)}</p><p>Different conditions can look alike from home. An examination helps narrow the possibilities and determine whether testing, treatment, monitoring, or referral is appropriate.</p><h2>When to seek care</h2><p>Prompt care is appropriate when signs cause pain, recur, worsen, interfere with eating or movement, or come with marked lethargy. Trouble breathing, collapse, uncontrolled bleeding, major trauma, prolonged seizures, or inability to urinate require emergency care.</p>{related_cards([(f"services/{service}.html",service_names[service]),("resources.html","Browse all educational resources"),("emergency-information.html","Emergency information")],2)}</article><aside class="page-aside"><h2>Care guides</h2><a href="ear-infections.html">Ear infections</a><a href="skin-allergies.html">Skin allergies</a><a href="vomiting-diarrhea.html">Vomiting and diarrhea</a><a href="pet-limping.html">Limping</a><a href="urinary-issues.html">Urinary issues</a><a class="button" href="../../contact.html#appointment">Request an appointment</a></aside></div></section>'''
 page(f"resources/conditions/{slug}.html",title,meta,title,"Condition guide",f'<a href="../../index.html">Home</a> / <a href="../../resources.html">Resources</a> / {escape(title)}',body,"resources",2)

for slug,name,role,interest,education,bio in team:
 body=f'''<section class="section section-paper"><div class="container profile-intro"><article class="prose"><h2>A thoughtful approach to care</h2><p>{escape(bio)}</p><p>Like every identity on this demonstration website, this profile is fictional and does not represent a real veterinary professional.</p><h2>How {escape(name.split()[0].replace('Dr.','Dr.'))} works with families</h2><p>Good plans begin with listening. Appointments make room for observations from home, clear explanations of findings, and questions about what is realistic for the pet and family.</p>{related_cards([("about.html","Return to About"),("services.html","Explore veterinary services"),("contact.html","Plan a visit")],1)}</article><dl class="profile-facts"><dt>Role</dt><dd>{escape(role)}</dd><dt>Clinical interests</dt><dd>{escape(interest)}</dd><dt>Education</dt><dd>{escape(education)}</dd><dt>Status</dt><dd>Fictional demonstration profile</dd></dl></div></section>'''
 page(f"team/{slug}.html",name,f"Meet {name}, a fictional {role.lower()} profile created for the Fayetteville Animal Hospital demonstration site.",name,"Fictional team profile",f'<a href="../index.html">Home</a> / <a href="../about.html">About</a> / {escape(name)}',body,"about")

for slug,title,meta,h2,p1,p2 in support:
 body=f'''<section class="section section-paper"><div class="container content-shell"><article class="prose"><h2>{escape(h2)}</h2><p>{escape(p1)}</p><p>{escape(p2)}</p><h2>Questions are welcome</h2><p>Clear expectations make care easier. Contact the hospital for help choosing the right appointment type, preparing records, or understanding the next step. This site is a fictional development environment and cannot provide medical services.</p>{related_cards([("services.html","Explore services"),("resources.html","Browse pet resources"),("contact.html","Contact and appointments")],0)}</article><aside class="page-aside"><h2>Visit information</h2><a href="new-patients.html">New patients</a><a href="what-to-expect.html">What to expect</a><a href="payment-information.html">Payment information</a><a href="faq.html">FAQ</a><a href="emergency-information.html">Emergency information</a></aside></div></section>'''
 page(f"{slug}.html",title,meta,title,"Plan your visit",f'<a href="index.html">Home</a> / {escape(title)}',body,"",0)

def hub_card(url,kicker,title,text):
 return f'<article class="hub-card"><span class="eyebrow">{escape(kicker)}</span><h2>{escape(title)}</h2><p>{escape(text)}</p><a class="text-link" href="{url}">Learn more</a></article>'

service_cards=''.join(hub_card(f"services/{s}.html","Veterinary care",n,summary) for s,n,summary,*_ in services)
services_body=f'''<section class="section section-paper"><div class="container"><div class="category-heading"><div><span class="eyebrow">Complete care</span><h2>Services shaped around the whole story.</h2></div><p>Explore preventive, diagnostic, procedural, and life-stage care for dogs and cats.</p></div><div class="hub-grid">{service_cards}</div></div></section><section class="cta"><div class="container cta-inner"><h2>Not sure which visit to request?</h2><a class="button button-light" href="contact.html#appointment">Tell us what you’re noticing</a></div></section>'''
page("services.html","Veterinary Services","Explore preventive, dental, diagnostic, surgical, life-stage, and urgent veterinary care for dogs and cats.","Here for the routine—and the unexpected.","Connected care",'<a href="index.html">Home</a> / Services',services_body,"services",0)

article_cards=''.join(hub_card(f"resources/articles/{s}.html","Pet owner guide",t,m) for s,t,m,*_ in articles)
condition_cards=''.join(hub_card(f"resources/conditions/{s}.html","Condition guide",t,m) for s,t,m,*_ in conditions)
life_cards=''.join(hub_card(f"pet-care/{s}.html","Life-stage care",n,summary) for s,n,summary,*_ in life_stages)
resources_body=f'''<section class="section section-paper"><div class="container"><div class="category-heading"><div><span class="eyebrow">Life-stage library</span><h2>Care that changes as they do.</h2></div><p>Practical guidance for puppies, kittens, adults, and senior pets.</p></div><div class="hub-grid">{life_cards}</div></div></section><section class="section"><div class="container"><div class="category-heading"><div><span class="eyebrow">Owner education</span><h2>Questions worth exploring.</h2></div><p>General information to support better conversations with your veterinarian.</p></div><div class="hub-grid">{article_cards}</div></div></section><section class="section section-paper"><div class="container"><div class="category-heading"><div><span class="eyebrow">Care and condition guides</span><h2>Understand what you’re noticing.</h2></div><p>These guides educate without diagnosing and explain when professional evaluation matters.</p></div><div class="hub-grid">{condition_cards}</div></div></section>'''
page("resources.html","Pet Care Resources","Explore practical veterinary articles, life-stage guidance, and common condition guides for dog and cat owners.","Good questions are good care.","The field guide",'<a href="index.html">Home</a> / Resources',resources_body,"resources",0)

team_cards=''.join(hub_card(f"team/{s}.html",role,n,interest) for s,n,role,interest,*_ in team)
support_cards=''.join(hub_card(f"{s}.html","Visit information",t,m) for s,t,m,*_ in support)
about_body=f'''<section class="section section-paper"><div class="container split"><div class="image-panel"><img src="images/exam-room-cat.jpg" alt="A veterinarian spending time with a tabby cat and the cat's owner"></div><div><span class="eyebrow">Our philosophy</span><h2>Clinical rigor. Human warmth.</h2><p class="lead">Pets tell us plenty when we make time to observe, listen, and connect the clues.</p><p>We translate findings into clear choices—without rushed explanations or one-size-fits-all plans. The hospital and every person represented here are fictional.</p></div></div></section><section class="section section-forest"><div class="container"><div class="category-heading"><div><span class="eyebrow">Our fictional team</span><h2>Different strengths. One standard of care.</h2></div><p style="color:#d8dfd9">Every identity, credential, and biography is invented for this demonstration.</p></div><div class="hub-grid">{team_cards}</div></div></section><section class="section"><div class="container"><div class="category-heading"><div><span class="eyebrow">Before your visit</span><h2>Know what to expect.</h2></div><p>Useful information for planning care at our fictional hospital.</p></div><div class="hub-grid">{support_cards}</div></div></section>'''
page("about.html","About Our Practice","Learn about the philosophy, fictional team, and relationship-centered care at Fayetteville Animal Hospital.","Medicine is personal.","A practice with a point of view",'<a href="index.html">Home</a> / About',about_body,"about",0)

all_pages=[Path("index.html"),Path("about.html"),Path("services.html"),Path("resources.html"),Path("contact.html")]
all_pages += [Path("services")/f"{s[0]}.html" for s in services]
all_pages += [Path("pet-care")/f"{s[0]}.html" for s in life_stages]
all_pages += [Path("resources/articles")/f"{s[0]}.html" for s in articles]
all_pages += [Path("resources/conditions")/f"{s[0]}.html" for s in conditions]
all_pages += [Path("team")/f"{s[0]}.html" for s in team]
all_pages += [Path(f"{s[0]}.html") for s in support]

sitemap=['<?xml version="1.0" encoding="UTF-8"?>','<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
sitemap += [f"  <url><loc>{BASE}{'' if str(p)=='index.html' else str(p)}</loc></url>" for p in all_pages]
sitemap.append('</urlset>')
(ROOT/'sitemap.xml').write_text('\n'.join(sitemap)+'\n',encoding='utf-8')

notes=f'''# CrawlMetric Expanded Clean Baseline

This repository contains the expanded, technically clean baseline for the future CrawlMetric controlled testing environment. It contains **{len(all_pages)} indexable HTML pages** and intentionally includes no test defects.

## Architecture

- 5 core pages: Home, About, Services, Resources, and Contact
- {len(services)} detailed service pages under `/services/`
- {len(life_stages)} life-stage guides under `/pet-care/`
- {len(articles)} owner education articles under `/resources/articles/`
- {len(conditions)} care and condition guides under `/resources/conditions/`
- {len(team)} fictional team profiles under `/team/`
- {len(support)} visit-planning and supporting pages at the site root

The architecture uses hub-and-spoke internal linking. Services, Resources, and About are primary hubs; deeper pages include breadcrumbs, contextual links, related content, and appointment pathways. The main navigation remains intentionally compact.

## Clean-baseline status

- Unique titles, meta descriptions, H1s, and canonical URLs are required sitewide.
- Canonicals use `{BASE}`.
- Relative links and assets support GitHub Pages project hosting.
- `robots.txt` allows crawling and points to the full XML sitemap.
- The fictional-practice disclosure appears in the footer throughout the expanded templates.
- No intentional SEO, accessibility, indexability, schema, link, or content defects have been introduced.

## CrawlMetric workflow

This expanded site is intended to be crawled with Screaming Frog and recorded as the clean baseline before any controlled defects are added. Preserve this state in version control so later experiments remain reversible and measurable. Record every future controlled issue in `test-matrix.md` before implementation.
'''
(ROOT/'testing/baseline-notes.md').write_text(notes,encoding='utf-8')

for filename in ("index.html", "contact.html"):
 current=(ROOT/filename).read_text(encoding="utf-8")
 current=current.replace("https://fayettevilleanimalhospital.example/",BASE)
 current=current.replace("https://fayettevilleanimalhospital.example/contact.html",BASE+"contact.html")
 if filename == "index.html":
  current=current.replace('services.html#wellness','services/wellness-exams.html')
  current=current.replace('services.html#dental','services/dental-care.html')
  current=current.replace('services.html#diagnostics','services/diagnostics.html')
  current=current.replace('services.html#urgent','services/urgent-sick-care.html')
  current=current.replace('about.html#team','about.html')
 (ROOT/filename).write_text(current,encoding="utf-8")
print(f"Built {len(all_pages)} HTML pages")
